import type { IPaper } from '../../types'

/** Stable, reviewed metadata; the generated feed may refresh independently. */
export const simvlaPaper: IPaper = {
  arxivId: '2610.11248',
  title: 'SimVLA: Zero-Shot Sim-to-Real VLA Learning for Mobile Manipulation',
  titleZh: 'SimVLA：面向移动操作的零样本仿真到真实视觉语言动作学习',
  authors: ['Kyoungin Baik', 'Youngwoon Lee'],
  date: '2026-10-08',
  score: 14,
  keywords: ['移动操作', '轮式机械臂', 'VLA', '仿真到真机', '合成数据', '底盘与机械臂协同'],
  url: 'https://arxiv.org/abs/2610.11248',
  sourceUpdatedAt: '2026-10-08',
  sourceAbstract: `Large-scale, diverse datasets have driven the success of LLMs and VLMs. But VLAs for robotics remain limited by the cost and complexity of real-world data collection. While simulation offers a scalable alternative, its potential for sim-to-real VLA learning in mobile manipulation remains largely underexplored. We introduce SimVLA, an end-to-end framework that trains VLAs entirely on synthetic simulation data without teleoperation for mobile manipulation. SimVLA is first pre-trained on two complementary simulation-derived datasets: SimAction, a large-scale robot action dataset spanning 35 diverse mobile manipulation tasks, generated by composing atomic skills, and SimVQA, which leverages privileged simulator state to provide spatial, geometric, and subtask-level visual-language supervision. We further post-train SimVLA on a mixture of SimAction and SimDeploy, a dataset collected from policy rollouts across diverse simulated environments. We evaluate SimVLA on tasks including restocking, pouring, and cleaning, and show zero-shot transfer to real-world mobile manipulation, including real home environments. SimVLA outperforms policies trained on 50 in-domain real-world demonstrations, suggesting that simulation can enable scalable sim-to-real mobile manipulation. We further demonstrate the value of multiple complementary forms of supervision for effectively leveraging simulation in VLA training.`,
  summary: 'SimVLA 把程序生成的移动操作轨迹、仿真空间问答和策略在仿真中的自滚动轨迹组成两阶段训练链，并在三轮全向底盘双臂 Anubis 上验证。策略没有使用真实任务示范训练，但仿真硬件参数仍依赖真机校准序列；论文训练权重和完整配方尚未公开。',
  enrichmentStatus: 'curated',
  summaryLanguage: 'zh',
  analysisBasis: 'full-text',
  methodSummary: 'SimAction 用技能组合与运动规划造 23 维连续动作，SimVQA 提供特权空间监督；先隔离 flow 梯度做多任务预训练，再混合 SimAction/SimDeploy 做联合后训练。',
  keyPoints: [
    '直接契合 MFM-VL 第二阶段：在轮式底盘与双臂之间学习搜索、导航和实体操作的长时程协同。',
    'SimAction 约 20 万条/2,778 小时，SimVQA 约 100 万对，SimDeploy 约 2.2 万条/460 小时；论文并未证明全量数据和训练权重已公开。',
    '真实家庭只测两项任务、各十次；模拟厨房同分布下 200 条真机示范微调的基线仍优于 SimVLA。',
    '真机载体是三轮全向底盘双臂，不是轮足机械狗；轮足 WBC 需要单独建模和验证。',
  ],
  relatedWork: [
    { type: '同方向', title: 'Mobile ALOHA: Learning Bimanual Mobile Manipulation with Low-Cost Whole-Body Teleoperation', arxivId: '2401.02117' },
    { type: '互补', title: 'VOMMI: Collecting and Leveraging Portable Demonstrations for Mobile Manipulation', arxivId: '2610.08220' },
    { type: '互补', title: 'ManiUnit: A Manipulation Skill Dataset and Benchmark for Long-Horizon Tasks', arxivId: '2610.12089' },
    { type: '互补', title: 'LLA-MPPI: Rapidly Adaptive Whole-body Control of Legged Robots with GPU-Accelerated Parallel Simulations', arxivId: '2610.10465' },
  ],
  verifiedEmbodiment: {
    stage: 'wheeled',
    label: '三轮全向底盘＋双臂 Anubis · 真机验证',
    detail: '官方 v1 正文 §4.2 与附录 H/Table 10 明确 Anubis 为三轮全向移动底盘，双臂各 6 自由度，配夹爪和腕部相机；论文没有轮足载体实验。',
    sourceUrl: 'https://arxiv.org/html/2610.11248v1#A8',
    locator: '§4.2；附录 H Robot Hardware Spec / Table 10',
  },
}
